<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\StockOS.Domain\StockOS.Domain.csproj" />
    <ProjectReference Include="..\StockOS.Application\StockOS.Application.csproj" />
    <ProjectReference Include="..\StockOS.Infrastructure\StockOS.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <!-- Permite compilar la referencia de Windows Forms en Linux/macOS -->
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

</Project>
